# Generated by Django 2.1.5 on 2019-02-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxp', '0003_auto_20190214_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
