# Generated by Django 2.1.5 on 2019-02-14 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oxp', '0006_auto_20190214_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oxp.Product'),
        ),
        migrations.AlterField(
            model_name='images',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oxp.Service'),
        ),
    ]
