# Generated by Django 2.1.5 on 2019-02-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxp', '0008_auto_20190214_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
