# Generated by Django 2.1.5 on 2019-03-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxp', '0012_service_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
