# Generated by Django 2.1.5 on 2019-03-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxp', '0013_auto_20190303_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
